path: D:/road_yolo_detect

train: train/images
val: valid/images

nc: 12

names:
  0: 아스팔트 도로파임
  1: 콘크리트 도로파임
  2: 종방향균열
  3: 횡방향균열
  4: 거북등균열
  5: 줄눈부파손
  6: 십자파손
  7: 절삭보수부파손
  8: 긴급보수부파손
  9: 규제봉
  10: 맨홀
  11: 배수로
